
// Nato Character Set
// ref: https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

exports.separator = ", ";

exports.set = [
    {letter:"A",word:"Alpha"},
    {letter:"B",word:"Bravo"},
    {letter:"C",word:"Charlie"},
    {letter:"D",word:"Delta"},
    {letter:"E",word:"Echo"},
    {letter:"F",word:"Foxtrot"},
    {letter:"G",word:"Golf"},
    {letter:"H",word:"Hotel"},
    {letter:"I",word:"India"},
    {letter:"J",word:"Juliet"},
    {letter:"K",word:"Kilo"},
    {letter:"L",word:"Lima"},
    {letter:"M",word:"Mike"},
    {letter:"N",word:"November"},
    {letter:"O",word:"Oscar"},
    {letter:"P",word:"Papa"},
    {letter:"Q",word:"Quebec"},
    {letter:"R",word:"Romeo"},
    {letter:"S",word:"Sierra"},
    {letter:"T",word:"Tango"},
    {letter:"U",word:"Uniform"},
    {letter:"V",word:"Victor"},
    {letter:"W",word:"Whiskey"},
    {letter:"X",word:"X-ray"},
    {letter:"Y",word:"Yankee"},
    {letter:"Z",word:"Zulu"},
    {letter:"0",word:"Zero"},
    {letter:"1",word:"One"},
    {letter:"2",word:"Two"},
    {letter:"3",word:"Three"},
    {letter:"4",word:"Four"},
    {letter:"5",word:"Five"},
    {letter:"6",word:"Six"},
    {letter:"7",word:"Seven"},
    {letter:"8",word:"Eight"},
    {letter:"9",word:"Nine"},
    {letter:"-",word:"Dash"},
    {letter:"/",word:"Stroke"},
    {letter:".",word:"Dot"},
    {letter:":",word:"Colon"},
    {letter:";",word:"SemiColon"},
    {letter:"@",word:"At"}
];
