
// Western Character Set

exports.separator = ", ";

exports.set = [
    {letter:"A",word:"Adams"},
    {letter:"B",word:"Boston"},
    {letter:"C",word:"Chicago"},
    {letter:"D",word:"Denver"},
    {letter:"E",word:"Easy"},
    {letter:"F",word:"Frank"},
    {letter:"G",word:"George"},
    {letter:"H",word:"Henry"},
    {letter:"I",word:"Ida"},
    {letter:"J",word:"John"},
    {letter:"K",word:"King"},
    {letter:"L",word:"Lincoln"},
    {letter:"M",word:"Mary"},
    {letter:"N",word:"New York"},
    {letter:"O",word:"Ocean"},
    {letter:"P",word:"Peter"},
    {letter:"Q",word:"Queen"},
    {letter:"R",word:"Roger"},
    {letter:"S",word:"Sugar"},
    {letter:"T",word:"Thomas"},
    {letter:"U",word:"Union"},
    {letter:"V",word:"Victor"},
    {letter:"W",word:"William"},
    {letter:"X",word:"X-ray"},
    {letter:"Y",word:"Young"},
    {letter:"Z",word:"Zebra"},
    {letter:"0",word:"Zero"},
    {letter:"1",word:"One"},
    {letter:"2",word:"Two"},
    {letter:"3",word:"Three"},
    {letter:"4",word:"Four"},
    {letter:"5",word:"Five"},
    {letter:"6",word:"Six"},
    {letter:"7",word:"Seven"},
    {letter:"8",word:"Eight"},
    {letter:"9",word:"Nine"},
    {letter:"-",word:"Dash"},
    {letter:"/",word:"Stroke"},
    {letter:".",word:"Dot"},
    {letter:":",word:"Colon"},
    {letter:";",word:"SemiColon"},
    {letter:"@",word:"At"}
];
